name: Publish Inference Experimental Wheels to PyPi
on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      publish:
        description: "Actually publish the package to PyPI"
        required: false
        default: false
        type: boolean
      pre_release:
        description: "Mark as pre-release"
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on:
      labels: depot-ubuntu-22.04-small
      group: public-depot
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
      - name: 📦 Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('inference_experimental/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ matrix.python-version }}-
      - name: 🐍 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
      - name: 📦 Install dependencies
        working-directory: inference_experimental
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          python -m uv build
      - name: 📤 Publish to PyPI
        if: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish == true) }}
        working-directory: inference_experimental
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ "${{ github.event.inputs.pre_release }}" != "true" ]]; then
              echo "Error: Non-prerelease publishing is only allowed on release events"
              exit 1
            fi
            echo "Publishing to PyPI as a pre-release"
            python -m uv publish --check-url https://pypi.org/simple/ --prerelease
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            echo "Publishing to PyPI"
            python -m uv publish --check-url https://pypi.org/simple/
          else
            echo "Error: Unexpected event type: ${{ github.event_name }}"
            exit 1
          fi
